### ISSUE TITLE
[Firefox] Error when using Tab created using the "Send tab to device" function.

### ISSUE THREAD

**Issue by optoisolated** [gab-ai-inc/gab-dissenter-extension#13]
When a tab is sent to another browser, and Dissenter is opened with that tab open, we receive the following error:

> "Cannot read property '_id' of null"

This occurs even after copy pasting the URL into a New Tab, and even closing and opening the browser, so it appears to be caching it somehow. When pasting the URL of the tab directly into the Dissenter.com page for viewing, it opens fine.

The error has been replicated on several devices running Firefox.

**Comment by optoisolated** [comment]
The issue seems to be most repeatable on pages/sites where there currently are no comments (new sites). Existing pages seem to not be as affected.

**Comment by harrymmmm** [comment]
I started seeing this error just clicking the extension when viewing some URLs. 
On the dissenter home page, copying that same URL produces the desired effect.

**Comment by mgabdev** [comment]
Thanks for submitting an issue. This has been fixed. It was only occurring on new URLs with no comments. Was related to the new logic that counts the number of posts on a URL for display.
https://twitter.com/getongab/status/1101871346441568257
