### ISSUE TITLE
Postings wont post on dissenter.com

### ISSUE THREAD

**Issue by marwal88** [gab-ai-inc/gab-dissenter-extension#15]
Using Brave browser, I can not publish on https://dissenter.com
![dissenter](https://user-images.githubusercontent.com/42113907/53682580-70e2a100-3cf7-11e9-80bd-454414198272.PNG)

When I press "Publish", the post seems to get published. When I revisit, it is not published and I am presented with the same message in the form.

**Comment by optoisolated** [comment]
I suspect this is the same as issue #13

**Comment by mgabdev** [comment]
Closing as this is duplicate to #13 (and it has been resolved)
