### ISSUE TITLE
Bug: Unable to access settings UI

### ISSUE THREAD

**Issue by gabrielalack** [gab-ai-inc/gab-dissenter-extension#18]
- When attemping to edit settings, I am getting an error
<img width="411" alt="screen shot 2019-03-02 at 4 30 34 pm" src="https://user-images.githubusercontent.com/3742245/53688371-a2b03380-3d08-11e9-8dbb-41840a8e81c5.png">

- Also: profile changes made on gab.com are not migrating into dissenter until I log out and log back in again.

**Comment by mgabdev** [comment]
Hi @gabrielalack Can you please confirm if you are still seeing this issue still? I cannot replicate this this issue on the newer version. Thanks.

**Comment by mgabdev** [comment]
Closing this as it is no longer an issue.
