### ISSUE TITLE
[Firefox] "Cannot read property 'flags' of undefined"

### ISSUE THREAD

**Issue by llirium** [gab-ai-inc/gab-dissenter-extension#21]
"Cannot read property 'flags' of undefined" appears as an error when either opening the FIrefox Dissenter extension, or visiting the dissenter.com website.  I'm unable to Log In with either the website or the button on the extension itself.

**Comment by mgabdev** [comment]
Hi @llirium are you still experiencing this issue in our latest version?

**Comment by mgabdev** [comment]
Closing this issue as it has not been an issue in the latest version.
