### ISSUE TITLE
Option to allow extension in incognito mode is not available for chrome

### ISSUE THREAD

**Issue by cassiohg** [gab-ai-inc/gab-dissenter-extension#26]
On chrome, when going in the extensions details 
* top right Options > more tools > Extensions > Dissenter Extension > Details

there is no option to allow the app to run in chrome's incognito mode. This means the extension doesn't show up when using an incognito window.

**Comment by mgabdev** [comment]
Thank you for pointing this out. I will work on a solution to this issue.

**Comment by cassiohg** [comment]
It works in incognito mode now. Thank you.
