### ISSUE TITLE
Comments not visable, extension says "1 comments" but wont display it.

### ISSUE THREAD

**Issue by ethicalfive** [gab-ai-inc/gab-dissenter-extension#28]
I've been searching the @GabDissenter tag on gab to read dissenter comment threads and I've discovered that many of of the links I follow lead to the extension telling me there is "1 comments" but it doesn't display those comments.

I know they exist because I can see the comment that was written by the shared post about it to Gab. Maybe it's a problem with the "share to gab" check box or something else? Here is an example:

```

Romhacking.net - Home

Fun to see what weird hacks people are still doing to classic videogames these days. Plus there's often games being translated into English for the first time.

http://www.romhacking.net/
via @GabDissenter
ROMhacking.net News
Classic video game modifications, fan translations, homebrew, utilities, and learning resources.
www.romhacking.net
```
 But i've seen many more like this.

**Comment by ethicalfive** [comment]
Update - The author of this particular comment said that they hid the comment and thats why I couldn't see it, however I've seen this with so many comments, this cannot be the case for all of them. If I run into more examples, I'll post them up.

**Comment by skatahub** [comment]
I am now receiving the message "There are no comments at this time." on every site I visit even though it says there are X comments at the top of the Dissenter window.

For example, at CNN right now it says "182 comments" at the top, then lower down, just below the cnn.com URL it says "There are no comments at this time." and nothing is showing.

Yesterday I was seeing all comments.

I have just downloaded Crome and only installed Dissenter and had the same problem. I have the same in Opera too.

**Comment by ethicalfive** [comment]
Here is another example, says it has 3 comments, there is a  "There are no comments at this time."
https://cosmicbook.news/captain-marvel-mcu-doubt-avengers-unhappy

The shared to gab post:
```
 Rancid Lunchmeat @RancidLunchmeat
a few seconds ago
Captain Marvel MCU Future In Doubt; Avengers Cast Unhappy | Cosmic Book News

#CaptainMarvel generally and #BrieLarson specifically were both horrific choices to try to bring the #Marvel #MCU into it's second phase after retiring #Ironman #Hulk #Thor #CaptainAmerica, etc. #Disney has a complete shitshow on their hands and they know it after their #StarWars debacle.

https://cosmicbook.news/captain-marvel-mcu-doubt-a...
via @GabDissenter
Captain Marvel MCU Future In Doubt; Avengers Cast Unhappy
Disney CEO Bob Iger claimed to be upset with Kevin Feige.
cosmicbook.news
```
I guess this isn't really the extensions fault but the dissenter.com platform itself as I tried viewing them through the website and its the same story, saying there are comments but unable to see them.

**Comment by mgabdev** [comment]
Thank you for flagging this issue. Will look into appropriate design patterns for the website to make this less confusing for everyone.

**Comment by ethicalfive** [comment]
> Thank you for flagging this issue. Will look into appropriate design patterns for the website to make this less confusing for everyone.

Thank you! I actually figured out the mechanism for the bug. The comments aren't qualifying as a Top comments and so the Top/controversial/latest comments sorting button are being hidden and the comment section is treated as if no one has commented. I was able to make the comments visable by making my own comment, reloading the dissenter comments for that URL, now suddenly the Sorting buttons become visible and I am able to click on latest and see the other comments.

**Comment by ErikWallstrom** [comment]
I am not able to see any comment on any site

**Comment by ethicalfive** [comment]
It appears this particular issue has been resolved! The comment threads effected are still effected but new ones are working correctly from what I can see!

**Comment by BigTravis** [comment]
I am on Firefox and have noticed this as well, but it appears to be around certain words used. According to the FAQ, it says that the Chrome extension is censored, but I am not sure about Firefox.

**Comment by mgabdev** [comment]
Hi all, please reference the following issues as I believe they may be resolutions to these issues brought up in this thread: #62 #57 

Closing this issue out as it appears that those two tickets resolve the problems in this thread.

Feel free to open this back up if the issue props up again.
