### ISSUE TITLE
Safari popup does not update/ change URL

### ISSUE THREAD

**Issue by MaltYebisu** [gab-ai-inc/gab-dissenter-extension#3]
When switching to a different site, the popup does not update even when closing and re-opening the popup.

![dissenter](https://user-images.githubusercontent.com/37108951/53538939-e0963780-3b0f-11e9-8f71-e7a2bf725229.png)

As you can see, the Dissenter popup still says twitter.com even on the dissenter homepage.
Closing the Safari window did not help. 

This was on Dissenter Extension for Safari version 0.1.0 running on Safari Version 12.0.3 (14606.4.5) on macOS Mojave Version 10.14.3 (18D109).

I installed the plugin with the Extension Builder under the Develop menu as instructed by dissenter.com/download.

**Comment by mgabdev** [comment]
Thank you for submitting the issue and details. I can replicate. Will be working on a fix.

**Comment by scrutinizer11** [comment]
Hi, popping up here to say that I wasn't able to make it run on the newest Safari 12.0.3 in High Sierra, also on Safari 7.1.8 in Mavericks and Safari 5.1.7 in Lion (though with latter two OS'es it;s possible to run any other signed extension). In Extension Builder it says that the extension is not signed by the Safari extensions developer certificate and the icon is unclickable and greyed out. Upon the next restart it disappears from extensions pane but remains on the list of extensions in Extensions Builder.

**Comment by CommieChan** [comment]
Can't run it either in Safari 12.0.3 with High Sierra. 
same error as other guy point out with the warning icon and icon is not clickable and grayed. out.

**Comment by mgabdev** [comment]
Fixed the issue with the url not updating on new tabs with latest release (r4). 

Commit: 91ad5ca72a3b243e6c793056ff4ba88d05681995
