### ISSUE TITLE
Error 520 Cloudflare

### ISSUE THREAD

**Issue by StephenVivash** [gab-ai-inc/gab-dissenter-extension#31]
Ray ID: 4b44d8169f75946f • 2019-03-08 12:34:35 UTC 
Web server is returning an unknown error (Tokyo & Singapore)
Reported by the extension window (Edge) for days now, dissenter web site still works

**Comment by SouldomainTM** [comment]
Same here when clicking on the icon. Says browser working. Cloudfare Working.

Ray ID: 4b4aff0cb89a7d02 • 2019-03-09 06:29:45 UTC

**Comment by StephenVivash** [comment]
Fixed in r6
