### ISSUE TITLE
Comments don't show up on Gab anymore, even when check box is clicked

### ISSUE THREAD

**Issue by Copen-08** [gab-ai-inc/gab-dissenter-extension#37]
So, when I leave a comment and check the box to share on Gab it still doesn't share it. I tried on a article on Gematsu, but it didn't work. I'm on Android 9 and Firefox.

**Comment by mgabdev** [comment]
Hi @Copen-08 thank you for submitting an issue. I have just tested on the latest version and it worked. Can you please confirm if you are still witnessing this error?

**Comment by mgabdev** [comment]
Closing this issue as it does not exist in latest Dissenter version.
