### ISSUE TITLE
Can't get the extension to work on Edge

### ISSUE THREAD

**Issue by Eirenarch** [gab-ai-inc/gab-dissenter-extension#38]
I don't know if this is actual bug or something with my configuration but I can't get the extension to work on Edge. When I open it I only see the loading image and nothing happens. If I click on "inspect popup" the console contains this

CONSOLE21301: serviceWorker.getRegistrations is rejected due to unsecure context or host restriction in ms-browser-extension://DissenterExtension_38934B2267E44D4A958195D27ADD1554/popup/popup.html.

Extension version 0.1.4, Edge version 44.17763.1.0

**Comment by mgabdev** [comment]
Hi @Eirenarch thank you for submitting an issue. Will investigate this issue.

**Comment by mgabdev** [comment]
Hi @Eirenarch, in the latest release of r9, the Dissenter Microsoft Edge extension is now working. https://github.com/gab-ai-inc/gab-dissenter-extension/releases/tag/r9
