### ISSUE TITLE
No "Dissent this" button on Twitter new layout

### ISSUE THREAD

**Issue by julianodorneles** [gab-ai-inc/gab-dissenter-extension#39]
There isn't "Dissent this" button when using Twitter's new layout.
![Captura de tela de 2019-03-13 16-43-43](https://user-images.githubusercontent.com/348090/54309625-445c3e00-45af-11e9-84c0-95388101868d.png)

**Comment by mgabdev** [comment]
Thanks for creating an issue for this. Will be fixing for the next release.

**Comment by mgabdev** [comment]
This issue has been resolved with the latest release.
View content script for Twitter V2 dissent button code here: https://github.com/gab-ai-inc/gab-dissenter-extension/blob/master/src/scripts/content/twitter/script-v2.js

Closing this issue.
