### ISSUE TITLE
Opening Dissenter extension on a "New Tab" causes a "Cannot read property 'slice' of null" error.

### ISSUE THREAD

**Issue by optoisolated** [gab-ai-inc/gab-dissenter-extension#41]
Opening the Dissenter extension on a "New Tab" causes a "Cannot read property 'slice' of null" error. When opening on a blank tab, the extension page should probably just open to the Dissenter home page rather than displaying the above error.

**Comment by mgabdev** [comment]
Hi @optoisolated can you please input what browser and version of the browser are you using?

**Comment by optoisolated** [comment]
This was noticed on [FireFox] 65.0.2

**Comment by mgabdev** [comment]
@optoisolated Thank you. I can replicate this issue. Will be working to resolve.

**Comment by mgabdev** [comment]
@optoisolated This issue has been resolved in the latest release of r9. https://github.com/gab-ai-inc/gab-dissenter-extension/releases/tag/r9
