### ISSUE TITLE
(suggestion) Icon's colour

### ISSUE THREAD

**Issue by ubone** [gab-ai-inc/gab-dissenter-extension#46]
change the chat bubble's colour of the toolbar's icon to white for visibility
like the one on the top left of the pop up window

**Comment by mgabdev** [comment]
Hi @ubone do you mean the website's logo in the top left or the logo for the extension that is visible on, say, our Chrome extension page here: https://chrome.google.com/webstore/detail/dissenter-extension/gdmekeodmghijamlkjcfpigdcdmcllbo?hl=en ?

**Comment by ubone** [comment]
no i mean the toolbar icon on the right of firefox's address bar

**Comment by mgabdev** [comment]
The Dissenter logo has been updated. Closing this issue.
