### ISSUE TITLE
[Edge] Manifest parsing error: Missing 'author' field.

### ISSUE THREAD

**Issue by SouldomainTM** [gab-ai-inc/gab-dissenter-extension#5]
I can't load v011 at all.

**Comment by coldacid** [comment]
@SouldomainTM for now you can open up manifest.json and replace its contents with the following (the current file content plus the missing author property):

```json
{"author":"Gab","manifest_version":2,"name":"Dissenter Extension","short_name":"Dissenter","description":"Dissenter is the comment section of the Internet.","homepage_url":"https://dissenter.com","icons":{"16":"assets/images/logo/icon-16.png","48":"assets/images/logo/icon-48.png","128":"assets/images/logo/icon-128.png"},"permissions":["activeTab","https://*.dissenter.com/*"],"browser_action":{"default_icon":"assets/images/logo/icon-128.png","default_popup":"popup/popup.html"},"commands":{"_execute_browser_action":{"suggested_key":{"default":"Alt+Shift+D","mac":"Alt+Shift+D"}}},"background":{"scripts":["background/background.js"],"persistent":false},"content_security_policy":"script-src 'self' 'unsafe-eval'; object-src 'self' https://*.dissenter.com/*","version":"0.1.1"}
```

**Comment by mgabdev** [comment]
@coldacid Is the `author` field the only field that needs to be added and then the edge extension will be error free?

**Comment by coldacid** [comment]
Yep. After adding it, I am able to kiss the extension properly.

**Comment by SouldomainTM** [comment]
> @SouldomainTM for now you can open up manifest.json and replace its contents with the following (the current file content plus the missing author property):
> {"author":"Gab","manifest_version":2,"name":"Dissenter Extension","short_name":"Dissenter","description":"Dissenter is the comment section of the Internet.","homepage_url":"https://dissenter.com","icons":{"16":"assets/images/logo/icon-16.png","48":"assets/images/logo/icon-48.png","128":"assets/images/logo/icon-128.png"},"permissions":["activeTab","https://*.dissenter.com/*"],"browser_action":{"default_icon":"assets/images/logo/icon-128.png","default_popup":"popup/popup.html"},"commands":{"_execute_browser_action":{"suggested_key":{"default":"Alt+Shift+D","mac":"Alt+Shift+D"}}},"background":{"scripts":["background/background.js"],"persistent":false},"content_security_policy":"script-src 'self' 'unsafe-eval'; object-src 'self' https://*.dissenter.com/*","version":"0.1.1"}

Thanks works for me.

**Comment by jordanmills** [comment]
Confirmed here, adding '"author":"Gab.ai",' (or similar, everything inside single quotes) just inside the first brace works fine.  Then it loads.  But there are other issues...

**Comment by mgabdev** [comment]
This has been fixed with the latest release (r4).

Commit: 10e18576397e8e09d926a7a88086e1f7a7173df6
