### ISSUE TITLE
Latest Version doesn't install in Waterfox

### ISSUE THREAD

**Issue by RealRaven2000** [gab-ai-inc/gab-dissenter-extension#54]
because of the new manifest file (and no install.rdf) the latest version installing on Waterfox release 56.2.8, is 0.1.1 - would it be possible to create a forked version "dissenter classic" for older browsers that has the additional features of 0.1.5 ? If not, could I release a forked version for the pale moon crowd?

**Comment by mgabdev** [comment]
Hi @RealRaven2000 thanks for the suggestion. Will be looking to implement Waterfox along with a few other browsers soon in future releases.

**Comment by BunnyTheLifeguard** [comment]
@mgabdev That would be great! I had Dissenter working on Waterfox when it was on Mozilla's extension website, but unfortunately I had to reset my laptop and now the manual install only stays until restart of the browser :(

**Comment by mgabdev** [comment]
@RealRaven2000 @BunnyTheLifeguard a Waterfox download has been added on https://dissenter.com/download

**Comment by BunnyTheLifeguard** [comment]
@mgabdev Wow, thank you so much for the quick update! :)

**Comment by RealRaven2000** [comment]
> 
> 
> @RealRaven2000 @BunnyTheLifeguard a Waterfox download has been added on https://dissenter.com/download

thanks very much ( I already made my own version but it's great to have the latest features ) much respect!!
