### ISSUE TITLE
Invalid URL on facebook post

### ISSUE THREAD

**Issue by LucasMW** [gab-ai-inc/gab-dissenter-extension#55]
I get Invalid URL when trying to dissent [this post](https://www.facebook.com/BFIDE/posts/1973082082740371?__xts__[0]=68.ARATJA-HJdn0d6yUWBA0JDip27ZCfCLmNd9_Km6CSAIIEN5XjTylvIfG5ydpoqEGVYUcd-kvMRfFQiIlmvpGAh7O3RH-l-7bQ83css-6OUYUfg3mk68dJxctWPul0z1faI4SnH6T-hX1jsUyO6-R6OdUnaz2ZqjWSh3uikvLVJZJnaJN-HpF5GeGetRly2JGmTO66Ty-EKAj5fohV8vyKWCCYyF4joIv6laGCAV3TC9EQG-OgNCLyn5qAXEnABQ3E_aQ54eb6lbctTB0HEp-Poe1wf9CHObxq6Vst3593ZYQABAmfqCgNg4F7qdUEjQtls8lSWPk8OqanSlstwqvlA&__tn__=-R) on facebook:

It probably means we can't comment on specific posts on facebook. Maybe only posts from facebook pages.

**Comment by LucasMW** [comment]
When I modify the url, leaving just [this](https://www.facebook.com/BFIDE/posts/1973082082740371)
Dissenter works. But I did have to change the URL manually

**Comment by mgabdev** [comment]
Hi @LucasMW this is indeed working as expected. In your first comment, the [first URL](https://www.facebook.com/BFIDE/posts/1973082082740371?__xts__%5B0%5D=68.ARATJA-HJdn0d6yUWBA0JDip27ZCfCLmNd9_Km6CSAIIEN5XjTylvIfG5ydpoqEGVYUcd-kvMRfFQiIlmvpGAh7O3RH-l-7bQ83css-6OUYUfg3mk68dJxctWPul0z1faI4SnH6T-hX1jsUyO6-R6OdUnaz2ZqjWSh3uikvLVJZJnaJN-HpF5GeGetRly2JGmTO66Ty-EKAj5fohV8vyKWCCYyF4joIv6laGCAV3TC9EQG-OgNCLyn5qAXEnABQ3E_aQ54eb6lbctTB0HEp-Poe1wf9CHObxq6Vst3593ZYQABAmfqCgNg4F7qdUEjQtls8lSWPk8OqanSlstwqvlA&__tn__=-R) contains a long string of characters as the end within the query parameters of the URL whereas the [second url](https://www.facebook.com/BFIDE/posts/1973082082740371) does not contain all of the query parameters after the post id. 

Dissenter takes into account the entire URL as given. So if there are query parameters (i.e. example.com?query-parameter=test) that will be different than a url without query parameters (i.e. example.com). 

Hope this clears it up! Closing this issue.
