### ISSUE TITLE
Share to Gab, success, but edit does not propagate to Gab post

### ISSUE THREAD

**Issue by sgornick** [gab-ai-inc/gab-dissenter-extension#56]
Dissenter v0.1.5, on Chromium v73.

If I mark the checkbox "Share to Gab", my comment does create a post on both Dissenter.com/user/[me]  as well as on Gab.com/@[me]

Then when I click the [...] icon and select edit, I can change the comment and the revised version is what shows on that post on Dissenter.com/user/[me], however those changes did not propagate to the post on Gab.com/@[me].

I can manually edit on Gab.com, but since this was a post using Dissenter with "Share to Gab", I was assuming the edit would occur on both Dissenter.com and Gab.com

**Comment by mgabdev** [comment]
Hi @sgornick thanks for submitting this issue. I understand the problem, though, this feature is working as expected. 

There currently does not exist a solution to allow for editing comments on Dissenter and for the Gab.com post shared from that comment to update alongside that. Once a gab is posted from a Dissenter comment it is its own entity and cannot be updated alongside that Dissenter comment. 

There also isn't an existing API for _editing_ posts on Gab. Only _posting_ new gabs.

Unfortunately with all that said, one would need to continue to manually edit any Gab posts independently of any Dissenter comments. Apologies for the inconvenience.
