### ISSUE TITLE
Firefox XPI package extension

### ISSUE THREAD

**Issue by HostFat** [gab-ai-inc/gab-dissenter-extension#58]
https://twitter.com/RandomFFUser/status/1116314310119178241

"The extension can be freely distributed on your own site. Here is an example https://github.com/andreicristianpetcu/gab-dissenter-extension/releases/ … click on dissenter_extension-0.1.5-fx.xpi It's a one click install. The devs need to spend 5 more minutes to make auto update work. Please ask the Mozilla community for help."

**Comment by jeroen7s** [comment]
This is definitely needed
While FF can block you from posting the Extension on their site, they can not block you from distributing the add-on yourself (unlike chrome)
no need for enabling dev mode and loading zip files "temporary"

**Comment by mgabdev** [comment]
Hi @HostFat, @jeroen7s thank you for the suggestion. I will work on implementing this for the next release.

**Comment by mgabdev** [comment]
@HostFat, @jeroen7s A Firefox XPI file has been distributed on the downloads page at https://dissenter.com/download and under the release for r9 at https://github.com/gab-ai-inc/gab-dissenter-extension/releases/tag/r9
