### ISSUE TITLE
Add support for .onion URLs and other alternative URL schemas

### ISSUE THREAD

**Issue by propolisor** [gab-ai-inc/gab-dissenter-extension#59]

**Comment by mgabdev** [comment]
Hi @propolisor upon testing a few .onion URLs they are working. (For instance: `https://dissenter.com/discussion/begin?url=http://wallstyizjhkrvmj.onion`) 

Can you please include some URLs as examples (.onion and any other alternative ones) that you believe are not supported?

**Comment by mgabdev** [comment]
Closing this issue as it appears that .onion urls work correctly in recent Dissenter build. Please feel free to reopen if there is any specific .onion url that is not working.
