### ISSUE TITLE
Since Google and Mozilla have removed this extension from their stores, perhaps it's time to stop playing nice

### ISSUE THREAD

**Issue by Tank-Missile** [gab-ai-inc/gab-dissenter-extension#62]
Removing the banned words list would be a start. So far I'm loving the extension, but for a platform that prides itself on free speech, this extension should not have a banned words list in any form. I installed the version from the dissenter website, so it's not just there for the sake of not being removed (oh the irony).

**Comment by mgabdev** [comment]
Good idea. 
This has been implemented.

https://twitter.com/getongab/status/1119049002975100930

Closing this issue.
