### ISSUE TITLE
Error message in extensions window after update

### ISSUE THREAD

**Issue by TrippyLogic** [gab-ai-inc/gab-dissenter-extension#68]
I just updated Dissenter since there was a message to do so, but I get an error in my extensions window. I use opera browser and there wasn't an error before the update.
It does seem to still work, but I think maybe the new updated thing does not. Anyway here's the error messages:

'chrome_url_overrides' is not allowed for specified extension ID.
`{"manifest_version":2,"name":"Dissenter Extension","short_name":"Dissenter","description":"Dissenter is the comment section of the Internet.","homepage_url":"https://dissenter.com","icons":{"16":"assets/images/logo/icon-16.png","48":"assets/images/logo/icon-48.png","128":"assets/images/logo/icon-128.png"},"permissions":["activeTab","https://*.dissenter.com/*"],"browser_action":{"default_icon":"assets/images/logo/icon-128.png","default_popup":"popup/popup.html"},"commands":{"_execute_browser_action":{"suggested_key":{"default":"Alt+Shift+D","mac":"Alt+Shift+D"}}},"background":{"scripts":["background/background.js"],"persistent":false},"content_scripts":[{"matches":["https://*.twitter.com/*"],"js":["content/twitter/script/script.js"],"run_at":"document_end"},{"matches":["https://*.youtube.com/*"],"js":["content/youtube/script/script.js"]},{"matches":["https://*.reddit.com/*"],"js":["content/reddit/script/script.js"]},{"matches":["https://*.wikipedia.org/*"],"js":["content/wikipedia/script/script.js"]},{"matches":["http://*/*","https://*/*"],"js":["content/all/script/script.js"]}],"content_security_policy":"script-src 'self' 'unsafe-eval'; object-src 'self' https://*.dissenter.com/*","incognito":"spanning","optional_permissions":["topSites"],"offline_enabled":false,"version_name":"0.1.6","version":"0.1.6","options_page":"options/options.html","update_url":"https://dissenter.com/dist/extensions/updates/chrome/manifest.xml","omnibox":{"keyword":"dissent"},"chrome_url_overrides":{"newtab":"newtab/newtab.html"}}
`
![dissenter1](https://user-images.githubusercontent.com/50031872/56836416-7b449580-6877-11e9-9945-565879be131d.PNG)
![dissenter2](https://user-images.githubusercontent.com/50031872/56836417-7b449580-6877-11e9-9eae-4bd2bc8ce83d.PNG)

**Comment by mgabdev** [comment]
Hi @TrippyLogic thanks for submitting this issue. With the latest releases, r10 & r11, the `chrome_url_overrides` key within the `manifest.json` file has been removed. Can you please confirm if you still experience this issue while using the latest releases?

**Comment by TrippyLogic** [comment]
The error message is gone and everything looks functional now, thanks :)
