### ISSUE TITLE
Dissenter plugin is setting the new tab behaviour

### ISSUE THREAD

**Issue by kabo** [gab-ai-inc/gab-dissenter-extension#69]
![Screenshot from 2019-04-27 11-34-07](https://user-images.githubusercontent.com/357601/56841226-ee500b00-687b-11e9-8191-d5a90621aaf9.png)

Plugin disabled until this behaviour can be disabled.

**Comment by gary9872** [comment]
If I wanted this, I'd download bonzai buddy.

**Comment by githubsux** [comment]
UH OH, Someone goofed up ! ;-) 
Not mine. I signed this myself using the old fork from ~1week ago. Can install it without any developer mode BS. [https://www.mediafire.com/file/434u2g3vr0v33l7/dissenter_extension-0.1.5-fx.xpi/](https://www.mediafire.com/file/434u2g3vr0v33l7/dissenter_extension-0.1.5-fx.xpi/) ^^

**Comment by TehSViN24** [comment]
but really now by doing this dissenter becomes nothing more than like that disgusting 2000s new tab malware

**Comment by mgabdev** [comment]
@kabo, @TehSViN24, @githubsux, @gary9872 in the latest release, r11, the Dissenter new tab experience has been made optional. It is off by default and can be toggled on from within the extension's options/preferences page.
