### ISSUE TITLE
More/custom search engines

### ISSUE THREAD

**Issue by BunnyTheLifeguard** [gab-ai-inc/gab-dissenter-extension#70]
Hey team, great job on the update and the new tab page.
The only thing which is bothering me is the choice of search engines.
As you can see [here](https://tools.privacymachine.info/search.html), even Duckduckgo is not recommended, since it is based in the US, only partially open source (when they stated otherwise) and is officially collaborating with Yahoo.

There are better search engines for privacy like [Qwant](https://www.qwant.com/) or instances of SearX [like this one](https://search.privacytools.io/).
The best thing would probably be to give the user a setting/field where he can input a url to the search engine of his choice.

**Comment by mgabdev** [comment]
Hi @BunnyTheLifeguard thanks for the suggestion. In the latest release r11, the Dissenter new tab experience has been made optional and if off by default. This can be re-enabled from within the options/preferences page. 

Also, Qwant has been added to the list of new tab search engines. This can be set from within the new tab page, within the search bar, click the caret all the way on the right to select a new default search engine.
