### ISSUE TITLE
Can I disable the Dissenter new tab in the new version? 

### ISSUE THREAD

**Issue by Lyeco** [gab-ai-inc/gab-dissenter-extension#71]
As much as most people in Dissenter use DuckDuckGo as their preferred search engine. I am one of the few who doesn't like it would prefer the default new tab experience and the google search engine.

Can we please give us an option to use the default tab rather than the dissenter tab? 

I can't use the extension right now because of it.

**Comment by pickx** [comment]
Let me disable this. This absolutely should not be bundled in with the extension.

**Comment by Lyeco** [comment]
> Let me disable this. This absolutely should not be bundled in with the extension.

I agree. I know that most users using Dissenter hate google but you have to let the non-haters have to choice not to use the new tab as well.

**Comment by MasterOfTheTiger** [comment]
Hey. It isn't "haters vs non haters". And not using Google doesn't mean you hate Google or are crazy about privacy. Okay.

**Comment by pickx** [comment]
Furthermore, just because I want to use Gab's service, does not mean I want them to inject stories into my new tab page. If I wanted to see "popular stories" and "recommended tabs" (which I assume Gab has a financial incentive to show me), I'd go visit www.dissenter.com myself. Tying this into an extension focused on freedom is a big no-no.

**Comment by gary9872** [comment]
> As much as most people in Dissenter use DuckDuckGo as their preferred search engine. I am one of >the few who doesn't like it would prefer the default new tab experience and the google search engine.

While I have nothing against DuckDuckGo, I prefer startpage.com and it hijacked that too. This concerns me. I also prefer Brave's new tab page, which I cannot use if I have dissenter enabled.

**Comment by danielb2** [comment]
I'm using another tool to manage my tab page. Dissenter screwed me up. Any way to disable this ?

**Comment by gary9872** [comment]
> I'm using another tool to manage my tab page. Dissenter screwed me up. this should be optional.
> 
> Anyway, the fix is: edit manifest.json and remove the section which concerns `newtab.html`
> 
> IOW, delete `,"chrome_url_overrides":{"newtab":"newtab/newtab.html"}` from the end of the manifest.json file in the root download.

Make sure to leave the last bracket though. When your editing is done the last couple of characters should look like this ,"keyword":"dissent"}}

**Comment by TehSViN24** [comment]
Anyone know how to disable it on firefox?
i have my own riced up minimal homepage and do not want this JS flat design ridden mess.
In any case i will have to uninstall dissenter until it is removed or separated to another add-on

**Comment by danielb2** [comment]
This has been fixed in 0.1.7

**Comment by Lyeco** [comment]
> This has been fixed in 0.1.7

When and how

**Comment by danielb2** [comment]
https://dissenter.com/dist/extensions/v0.1.7/dissenter_chrome.zip

**Comment by danielb2** [comment]
Five hours ago: https://github.com/gab-ai-inc/gab-dissenter-extension/releases/tag/r10

> Disabled new tab experience

**Comment by mgabdev** [comment]
@Lyeco, @danielb2, @pickx, @TehSViN24, @MasterOfTheTiger, @gary9872  in the latest release, r11, the Dissenter new tab experience has been made optional. It is off by default and can be toggled on from within the extension's options/preferences page.
