### ISSUE TITLE
Is ReCaptcha really a necessity to sign up?

### ISSUE THREAD

**Issue by SuperRobinHood** [gab-ai-inc/gab-dissenter-extension#72]
It's just so annoying. Solve a bunch of tricks to develop the Google AI for free and who knows when they will finally let you in, if ever. There's other less invasive security options.

**Comment by mgabdev** [comment]
Hi @SuperRobinHood - This is not an issue. We use recaptcha as one of a handful of ways to prevent the automated spamming of our platform.

**Comment by BradyThe** [comment]
I apologise for necromancing, but this is an issue if you care about privacy. It's also conflicting with the gab principle of standing up and offering an alternative to Silicon Valley.

Privacy friendly alternatives to reCAPTCHA do exist, https://captcheck.netsyms.com/ for example. ([Source](https://old.reddit.com/r/degoogle/wiki/index#wiki_recaptcha_replacement))

**Comment by ghost** [comment]
> We use recaptcha as one of a handful of ways to prevent the automated spamming of our platform.

We get this, but there are other open source and privacy-respecting alternatives which we can use.
