### ISSUE TITLE
Seperate or otherwise remove the new tab.

### ISSUE THREAD

**Issue by TehSViN24** [gab-ai-inc/gab-dissenter-extension#73]
I know you guys are making your own browser. But there is a big issue with changing the new tab for everyone else.

First of you must **never** add features that can be easily be set up using the native tools a browser like chromium provides you. Doing so will make the add-on needlessly bloated. Be like every other chromium fork and just change the new tab html.

If i wanted to have add-ons that change in any way my home page i would install malware. Stop the "feature" creep.

**I will setup my new page on my own thankyouverymuch:**
Ok frankly my set up of my start page is the best! Amazing! Yours? Not so good! Mine is fast in minimalist, yours is just bloated,slow and has a lot of silly animations!
SAD!

**Comment by mgabdev** [comment]
Hi @TehSViN24 in the latest release, r11, the Dissenter new tab experience has been made optional. It is off by default and can be toggled on from within the extension's options/preferences page.
