### ISSUE TITLE
"Cannot read property toLowerCase of null"

### ISSUE THREAD

**Issue by aggieben** [gab-ai-inc/gab-dissenter-extension#8]
After following the instructions in #5, I was able to install the extension into Edge.  However, now when I click the extension, the dialog that opens reports the error "Cannot read property toLowerCase of null".

![image](https://user-images.githubusercontent.com/1321/53614209-bdff2f80-3b9e-11e9-97d9-ae1a8cf1b09f.png)

**Comment by coldacid** [comment]
That's likely an issue with Dissenter itself. As far as I can tell what's shown in the popup is an actual page from the Dissenter website.

**Comment by jordanmills** [comment]
I'm seeing the same thing.  But the dissenter page works fine if I load it manually.  For example, opening the extension on this page shows that error (as it does for every other page).  But going to the link for this page (https://dissenter.com/discussion/begin?url=https%3A%2F%2Fgithub.com%2Fgab-ai-inc%2Fgab-dissenter-extension%2Fissues%2F8), it shows a dissenter page with no comments (as might be expected).

**Comment by mgabdev** [comment]
@aggieben Are you still witnessing this issue?

**Comment by aggieben** [comment]
No, but now it's just a dead progress indicator:
![image](https://user-images.githubusercontent.com/1321/54790791-6d12b200-4c05-11e9-9d04-a4aea400fb54.png)

Stays just like this indefinitely.

**Comment by coldacid** [comment]
I'm getting the same now with r7. Microsoft Edge 44.18351.1.0, EdgeHTML 18.18351 (Win10 Insiders version 1903, build 18351.7)

**Comment by jordanmills** [comment]
I'm getting the same thing with an older version of edge.

**Comment by mgabdev** [comment]
Hi all, in the latest release of r9, the Dissenter Microsoft Edge extension is now working. https://github.com/gab-ai-inc/gab-dissenter-extension/releases/tag/r9
