### ISSUE TITLE
500 Internal Server Error when trying to login (to either site or extension)

### ISSUE THREAD

**Issue by jdnixx** [gab-ai-inc/gab-dissenter-extension#83]
Might be a problem with Gab itself rather than Dissenter's site, but it's one of those (I guess not the extension itself). After hitting "Authorize" to my gab account when logging into Dissenter's site, either from the "log in" button on the extension or the site, I get this:
![image](https://user-images.githubusercontent.com/24235975/58436486-9fbca900-8093-11e9-96dd-21415ada7f97.png)

**Comment by justagoodperson** [comment]
Are you still getting this error? I've noticed the backend can spit out a lot of errors at times, some times worse than others. Let me know if it's still persisting or you were able to log in at a later point.

**Comment by jdnixx** [comment]
Seems to work for me now, thanks.

**Comment by rugabunda** [comment]
happens to me sporadically as well, directly on gab.com

**Comment by justagoodperson** [comment]
@rugabunda yeah it's just the backend spitting out an error for whatever reason, to fix it the devs would have to check their logs and maybe upgrade their servers
