### ISSUE TITLE
Dissenter Comment Count no longer visible

### ISSUE THREAD

**Issue by rugabunda** [gab-ai-inc/gab-dissenter-extension#93]
Was working fine for a few days, stopped a few days ago.

**Comment by Committing** [comment]
I believe the comment count was disabled due to users being afraid of it logging every page you visit to retrieve the count.

You may have to re-enable the count in the plugin again. (I use the Dissent browser so I'm not 100% on this)

Someone else correct me if I'm wrong.

**Comment by rugabunda** [comment]
ok I see, there is an option under addons/management called "comment badge enabled", enabling this shows the comment count again.
